//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaCalificada
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_RECETA
    {
        public int CREC_ID { get; set; }
        public int DREC_ID { get; set; }
        public int PROD_ID { get; set; }
        public decimal DREC_CANTIDAD { get; set; }
        public string DREC_INDICACION { get; set; }
    
        public virtual CAB_RECETA CAB_RECETA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}
