//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaCalificada
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class P2_PC1_TAD_2019IIEntities : DbContext
    {
        public P2_PC1_TAD_2019IIEntities()
            : base("name=P2_PC1_TAD_2019IIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAB_RECETA> CAB_RECETA { get; set; }
        public DbSet<DET_RECETA> DET_RECETA { get; set; }
        public DbSet<MEDICO> MEDICO { get; set; }
        public DbSet<PACIENTE> PACIENTE { get; set; }
        public DbSet<PRODUCTO> PRODUCTO { get; set; }
    }
}
