//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaCalificada
{
    using System;
    using System.Collections.Generic;
    
    public partial class PACIENTE
    {
        public PACIENTE()
        {
            this.CAB_RECETA = new HashSet<CAB_RECETA>();
        }
    
        public int PACI_ID { get; set; }
        public string PACI_DNI { get; set; }
        public string PACI_APE_PATERNO { get; set; }
        public string PACI_APE_MATERNO { get; set; }
        public string PACI_NOMBRE { get; set; }
    
        public virtual ICollection<CAB_RECETA> CAB_RECETA { get; set; }
    }
}
