//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticaCalificada
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        public PRODUCTO()
        {
            this.DET_RECETA = new HashSet<DET_RECETA>();
        }
    
        public int PROD_ID { get; set; }
        public string PROD_DESC { get; set; }
    
        public virtual ICollection<DET_RECETA> DET_RECETA { get; set; }
    }
}
